#define _GNU_SOURCE
#include <ncurses.h>
#include <stdio.h>
#include <math.h>
#include <arpa/inet.h>
#include <pty.h>
#include <utmp.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <sys/param.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <time.h>
#include <netdb.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "../../xtrafun/Includes/auxFuncs.h"
#include "../../xtrafun/Includes/nodes.h"
#include "../../xtrafun/Includes/comparator.h"
#include "../../xtrafun/Includes/hasher.h"
#include "../../xtrafun/Includes/cmdstruct.h"
#include "../../xtrafun/Includes/doublelist.h"
#include "../../xtrafun/Includes/stackList.h"
#include "../../xtrafun/Includes/dliterator.h"
#include "../../xtrafun/Includes/atomicOps.h"
#include "../../xtrafun/Includes/doublelistcomp.h"
#include "../../xtrafun/Includes/hashtablecomp.h"
#include "../../xtrafun/Includes/socketops.h"
#define SERVERLOGSX 50
#define SERVERLOGSY 0

