#define _GNU_SOURCE
#include <ncurses.h>
#include <stdio.h>
#include <math.h>
#include <arpa/inet.h>
#include <pty.h>
#include <utmp.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <sys/param.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <time.h>
#include <netdb.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "../../xtrafun/IncludesauxFuncs.h"
#include "../../xtrafun/Includesnodes.h"
#include "../../xtrafun/Includescomparator.h"
#include "../../xtrafun/Includeshasher.h"
#include "../../xtrafun/Includescmdstruct.h"
#include "../../xtrafun/Includesdoublelist.h"
#include "../../xtrafun/IncludesstackList.h"
#include "../../xtrafun/Includesdliterator.h"
#include "../../xtrafun/IncludesatomicOps.h"
#include "../../xtrafun/Includesdoublelistcomp.h"
#include "../../xtrafun/Includeshashtablecomp.h"
#define SERVERLOGSX 50
#define SERVERLOGSY 0

