#ifndef SOCKIO_H
#define SOCKIO_H

#define MAXNUMBEROFTRIES 10

#define CLIENT_TIMEOUT_CON_SEC 3
#define CLIENT_TIMEOUT_CON_USEC 1

#define CLIENT_TIMEOUT_DATA_SEC 3
#define CLIENT_TIMEOUT_DATA_USEC 1

#define SERVER_DROP_CHUNK_TIMEOUT_SEC 20
#define SERVER_DROP_CHUNK_TIMEOUT_USEC 0

#define SERVER_TIMEOUT_DATA_SEC 30
#define SERVER_TIMEOUT_DATA_USEC 1

#define SERVER_TIMEOUT_CON_SEC 3
#define SERVER_TIMEOUT_CON_USEC 1

#define HB_TIMEOUT_DATA_SEC 3
#define HB_TIMEOUT_DATA_USEC 1

#define HB_TIMEOUT_CON_SEC 3
#define HB_TIMEOUT_CON_USEC 1

#define BROWSER_TIMEOUT_DATA_SEC 3
#define BROWSER_TIMEOUT_DATA_USEC 1

#define BROWSER_TIMEOUT_CON_SEC 3
#define BROWSER_TIMEOUT_CON_USEC 1


#define MASTER_TIMEOUT_DATA_SEC 3
#define MASTER_TIMEOUT_DATA_USEC 1

#define MASTER_TIMEOUT_CON_SEC 3
#define MASTER_TIMEOUT_CON_USEC 1


#define HOLE_PUNCHING_TIMEOUT_SEC 0
#define HOLE_PUNCHING_TIMEOUT_USEC 1000000

#define REMAPPER_TIMEOUT_CON_SEC 2
#define REMAPPER_TIMEOUT_CON_USEC 3

#define REMAPPER_TIMEOUT_DATA_SEC 2
#define REMAPPER_TIMEOUT_DATA_USEC 3

typedef long unsigned int int_pair[2];
typedef unsigned char* buff_triple[3];


#endif
